### ISSUE TITLE
nemo: Can't search in documents

### ISSUE THREAD

**Issue by clefebvre** [linuxmint/-mint20.2-beta#1]
Results are not found in ODT, DOC, PDF.

**Comment by clefebvre** [comment]
The following packages are missing in the ISO:

```
poppler-utils
exif
id3
odt2txt
```

**Comment by clefebvre** [comment]
https://github.com/linuxmint/nemo/commit/5f10ff12f106988c34b4b5cd7889631fcefdf919

**Comment by Tibladar** [comment]
Why is it necessary to have these packages as hard dependencies and not as recommends as before?
Just so that they are included in the iso?

It contradicts the principle of dependencies, because these search helpers are not required, but are an additional feature.

For example, I don't ever need teX search, but I need to install over 100MB and results in issues like #58
