### ISSUE TITLE
release: Detailed instructions on update nofifications in the release notes?

### ISSUE THREAD

**Issue by jakoblm** [linuxmint/-mint20.2-beta#35]
It would be great if you could explain in more detail in the release notes how the update notifications work and what settings are available.  For example, in this comment and the following ones you have already explained in detail how to disable the notifications with "gsettings set com.linuxmint.updates tracker-disable-notifications true": https://blog.linuxmint.com/?p=4049#comment-194485

**Comment by jakoblm** [comment]
Can the notifications in the Update Manager be turned off completely by "Only show notifications for kernel and security updates"? Or does this only let you decide if you want to show notifications for all or only for security and kernel updates?

An easy way to turn it off in the GUI for experienced users would be nice.

**Comment by clefebvre** [comment]
> Can the notifications in the Update Manager be turned off completely by "Only show notifications for kernel and security updates"? Or does this only let you decide if you want to show notifications for all or only for security and kernel updates?

It's the latter. It only let you decide if you want to show notifications for all or only security/kernel.

> An easy way to turn it off in the GUI for experienced users would be nice.

There are two easy toggles already:

- The ability to disable automated checks
- The ability to disable the manager entirely

The configuration of the notification goes all the way to a whooping 90 days, that's an entire 3 month period without a single update being applied. I've asked for reasons on the blog why somebody would want to use resources to run such a manager every single day in the background, checking and using bandwidth every 2 hours for these 3 months and never ever apply a single update, and I wasn't given one yet.

I agree with the idea that as a new feature one would expect to be able to turn it off, I don't see the need for it though. 3 months is a huge amount of time. If someone hasn't applied an update in that long but still is open to the idea of maintaining the computer, then a reminder is definitely welcome. If the notification is not welcomed because updates are ignored on purpose, then there's no need to have the manager run in the background.

**Comment by jakoblm** [comment]
Okay that makes sense to me. Thanks for taking the time to clarify that.
