### ISSUE TITLE
Bulky : Can't remove subsequently with the same command

### ISSUE THREAD

**Issue by MenthaSuaveolens** [linuxmint/-mint20.2-beta#40]
1. Add a file
2. Select remove (keep the default)
3. Rename => Renaming is performed but Rename-button is greyed out 

Change one of the settings => Rename-button is active again

Note : The same issue when using "insert". In case of "change case" the greying out of the Rename-button is logical as the same change-case-operation will have no effect.

**Comment by clefebvre** [comment]
Please explain the issue a bit better, I can't understand it.. maybe add a screenshot, explain what you see, what you expect to see instead.

**Comment by MenthaSuaveolens** [comment]
1. Add a file, eg. doc.txt
2. "Insert"
3. Enter a text eg "a"
4. Rename => Renaming is performed but the Rename-button is greyed out after the renaming
Filename is renamed to adoc.txt : this is ok, suppose I want to insert an extra "a", I can't at a first glance because the rename-button is disabled. After changing any of the settings, eg. select a file to add, but don't add a file after all,the rename button gets active again.

I know it's far fetched an in most cases after the renaming it doesn't make sense to rename again, but for "insert" and "delete" it makes sense after all.

**Comment by clefebvre** [comment]
OK, I see your point. I'm not sure this needs fixing per se. It opens to other issues... if I leave the button active, I need to re-run the preview and that turns the right side of the pane into something different than the wanted result.

For instance, if you insert "a", you want to end up with "adoc.txt".

If I leave this button active after the rename, it won't do anything until I modify the options again to get a new preview of the new name.

If I automatically run a preview again after the rename, it will rename the file to "adoc.txt" but on the preview you'll see "aadoc.txt", i.e. it will be ready for you to click rename again.. but it will be confusing because what you see isn't what you renamed it to.
