### ISSUE TITLE
update manager, not translated text for pt-br

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/-mint20.2-beta#48]
in the "notifications" area, many texts are not translated even with the installed languages and the launchpad with 100% translated texts for pt-br.

Image:
https://postimg.cc/5YmsQ0D5

**Comment by xenopeek** [comment]
Translations from Launchpad weren't ready for the beta. Because of that the new notifications settings in mintupdate aren't translated on the beta. Before the final release is done the translations will be pulled again from Launchpad so if pt-br shows as 100% translated on Launchpad now it will be fine for the final release. So I'm closing this. If you manually downloaded and installed the latest translations from Launchpad and there's an issue with that this can be reopened.

**Comment by VaGNaroK** [comment]
> Translations from Launchpad weren't ready for the beta. Because of that the new notifications settings in mintupdate aren't translated on the beta. Before the final release is done the translations will be pulled again from Launchpad so if pt-br shows as 100% translated on Launchpad now it will be fine for the final release. So I'm closing this. If you manually downloaded and installed the latest translations from Launchpad and there's an issue with that this can be reopened.


I just received an update from the update manager, I applied it and it is already 100% translated to my language, so this bug report has already been fixed.

**Comment by xenopeek** [comment]
That update came earlier than I expected, thanks for the feedback!
