### ISSUE TITLE
CTRL+ALT+BACKSPACE Suspend Issue

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/-mint20.2-beta#50]
CTRL+ALT+BACKSPACE combination to restart Xorg is not working after suspend on Linux Mint 20.2 Beta Cinnamon.

**Comment by mtwebster** [comment]
I'm able to reproduce this, but not reliably.

Do you have multiple keyboard layouts enabled?

If you run `setxkbmap -print` you should see something like this if ctrl-alt-backspace assignment is working:
```
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+us+fr:2+de:3+inet(evdev)+group(alt_shift_toggle)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```
When it fails, you lose that trailing `terminate(ctrl_alt_bksp)`. I'm suspecting it's something to do with keyboard layout switching (when this configuration is reloaded probably). We only ever attempt to add our own mapping once at login, so if it does get reset, it's gone for good.

Try this:
```
gsettings set org.gnome.libgnomekbd.keyboard options "['terminate\tterminate:ctrl_alt_bksp']"
```

If you **are** using multiple keyboard layouts, you'll need to un-apply and then re-apply the switching shortcut, or any other custom settings you've made in the keyboard layout 'options' window.

Setting that in this manner makes sure it gets re-applied any time the configuration is reloaded. This is also, as mentioned, where any custom layout options are set as well, so we have to be able to add it in a way that doesn't upset anyone's existing configuration.

Instead of running setxkbmap once at login, we could add our terminate string to the existing setting entry at login.

**Comment by kelebek333** [comment]
Hi @mtwebster ,

This output after login.

```
setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+tr+inet(evdev)+terminate(ctrl_alt_bksp)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

This is after suspend.

```
setxkbmap -print
xkb_keymap {
	xkb_keycodes  { include "evdev+aliases(qwerty)"	};
	xkb_types     { include "complete"	};
	xkb_compat    { include "complete"	};
	xkb_symbols   { include "pc+tr+inet(evdev)"	};
	xkb_geometry  { include "pc(pc105)"	};
};
```

If I select `Key sequence to kill the X server` => `Ctrl+Alt+Backspace` , the issue is solved. 

![kill-x-server](https://user-images.githubusercontent.com/1300133/123552753-3599f500-d780-11eb-83f3-67afbcad4683.png)


So the issue is only with the `setxkbmap -option terminate:ctrl_alt_bksp` command in Startup Applications. This command is functional at login, but loses its functionality after suspend. 

I am using single keyboard layout. 

Thank you very much for your interest and efforts.

**Comment by clefebvre** [comment]
The following was done:

- Gsettings override used in MATE/Cinnamon to make Ctrl+Alt+Backspace kill Xorg
- Xsession.d used in Xfce to do the same
- XDG Autostarts removed
- Super+Space is now set in MATE/Cinnamon to switch layouts (not set in Xfce as it conflicts with Whisker menu)
- Super+Space shortcut removed from GWL in Cinnamon (was cycling thumbs)
