### ISSUE TITLE
Mintupdate: Is the countdown initialized?

### ISSUE THREAD

**Issue by vegam57** [linuxmint/-mint20.2-beta#54]
I have a question.
About the red line part of the attached image
Before the pop-up appears
When the next update is released, the app that was hitting the logic as the target of the next pop-up
Is the count days going to be initialized?
Example Firefox 89.0.0 →89.0.1 → **89.0.2** initialized?
![2021-06-24_15-32](https://user-images.githubusercontent.com/78515193/123215546-8b159e00-d503-11eb-80d0-a0250b58274e.png)

**Comment by Jeremy7701** [comment]
Will the current actions of "the orange dot" still be shown, regardless of these settings? I wouldn't normally wait a week or two before updating anything.

**Comment by vegam57** [comment]
My question is the logic of waiting for notification. It is not the logic that puts out orange dots.
Will notification be postponed further if new update of same app come out while waiting for notification?

**Comment by vegam57** [comment]
Why do I want to know so much detail?
This is because I want to accurately express the nuances of the original text when translate it.

**Comment by clefebvre** [comment]
Say:

- You're up to date
- Your setting is 7 days and you're logged in all that time
- Version 89.0.1 arrives on day 5
- Version 89.0.2 arrives on day 10

You will get a notification on day 7 because of Firefox (89.0.1).

Say you dismiss it twice (2 days cooldown in between)... that brings you to day 11 if my calculations are correct...

You'll then get a notification on day 11 because of Firefox (89.0.2).

You won't have to wait for day 17 in other words for 89.0.2 to trigger a notification, Firefox is outdated for more than 7 days, the version if tracked but it's not the deciding factor.

**Comment by vegam57** [comment]
Thank you for the commentary.
I deepened my understanding.
I will translate based on this understanding.

Original
Show a notification if an update has been available for (in logged-in days):
↓
My understanding
"Show a notification if any of the updates have not been applied over the number of days (in logged-in days):"
↓
My language
