### ISSUE TITLE
Mintupdate - no notifications

### ISSUE THREAD

**Issue by tomas-52** [linuxmint/-mint20.2-beta#62]
To see how notifications work I have set the preferences (in the order they appear in their window) to the following values:
Interface - Hide ... 0, Only ... 0
Auto-refresh ... I, - First ... 0, Then ... 2 minutes
Notifications - Only ... 0, Show ... 2, Show ... 2, Don't ... 2.
The last and only update for Mintupdate was applied on 2021-06-24-21:28 local time. Now I have 2021-06-26-22:58 and on boot and after I get no notification, just the icon with orange dot in tray. What is wrong ?!

(the info says e.g.
06.26@22:53 ++ Recurring refresh will happen in 0 day(s), 0 hour(s) and 1 minute(s)
06.26@22:54 ++ Starting refresh (local only)
06.26@22:55 ++ Found 42 software updates
06.26@22:55 ++ Refresh finished
When I installed the system on 2021-06-22-15:31 it already listed update to Intel-microcode 3.20210608...)

I think a notification should have been displayed.

**Comment by tomas-52** [comment]
Just by the way, where can I find the description of icons in the Type column of the update manager?

**Comment by xenopeek** [comment]
> Just by the way, where can I find the description of icons in the Type column of the update manager?

Hover the mouse cursor over an icon to show the icon's description.

**Comment by tomas-52** [comment]
Thank you for the advice.

A while ago I finally got the notification, as a result I must ask, how the delays in preferences are calculated.

**Comment by clefebvre** [comment]
Please take a screenshot of your preferences.

**Comment by tomas-52** [comment]
![obrazek](https://user-images.githubusercontent.com/86126554/123558993-c204e180-d799-11eb-8c31-7bacb90591cf.png)

Enclosed is the snapshot; after I finally got the notification I have done the update and then changed some of the preferences, for the snapshot I have tried to change them back but checking with the values described in yesterdays comment I see I have done one mistake - in Interface, Only should be 0 in place of I in the picture. (now there is 0 again and for recurring refresh I have set 6 hours).

**Comment by tomas-52** [comment]
Please note that the text for notifications has not been translated.

**Comment by xenopeek** [comment]
> Please note that the text for notifications has not been translated

Thanks. This issue was identified earlier, the new texts hadn't been sent to translation teams before start of the beta. That was remedied 2 weeks ago. You can review the translations status in mintupdate for your language here: https://translations.launchpad.net/linuxmint/latest/+pots/mintupdate/. New translations will be included in the final release.

**Comment by clefebvre** [comment]
There's a full 1 to 2 days precision gap due to the fact that the tracker only checks things once a day. You can look at what it records in ~/.linuxmint/mintupdate/updates.json.

I'll close this since it's not a release breaker. If you can find an issue in the way it records or interprets the records please report it at github.com/linuxmint/mintupdate.
