### ISSUE TITLE
release: System requirements

### ISSUE THREAD

**Issue by lhale78723** [linuxmint/-mint20.2-beta#77]
```
 * Cinnamon version (cinnamon --version)
   - Please specify if you are using the daily builds PPA
     (https://launchpad.net/~linuxmint-daily-build-team/+archive/ubuntu/daily-builds).
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
 * Graphics hardware *and* driver used
 * 32 or 64 bit
 * Attach ~/.xsession-errors, or /var/log/syslog
 ```

**Issue**
"System requirements:

1GB RAM (2GB recommended for a comfortable usage).
15GB of disk space (20GB recommended)." - we regularly see login loop problems due this spec

For Cinnamon, these specs are inadequate for decent operation. These specs haven't been updated since at least LM17. We've seen many problems in the forums related to these. Minimum System Requirements should read as follows:

2GB RAM (4GB recommended for comfortable usage).
30GB of disk space (50GB recommended). 

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Configuration info, if applicable**
If this bug report is related to an Applet, Desklet or Extension, please paste (or use a pastebin service) the offending extension's settings, if it has any.  You can obtain this by opening its configuration, clicking the 'hamburger' button in the upper-right corner of the window, and selecting "Export to a file". **Please be sure to review the contents and remove any personal data it may contain.**

```

Please paste here

```

**Comment by clefebvre** [comment]
Quick test in 20GB Vbox with 2GB RAM.

**RAM (1 terminal + 1 monitor open)**

- Cinnamon: 760MB
- MATE: 710MB
- Xfce: 675MB


**RAM (1 terminal + 1 monitor + 1 file browser + 1 Firefox page + 1 calculator + 1 spreadhseet + 1 text file)**

- Cinnamon: 1.3GB
- MATE: 1.2GB
- Xfce: 1.2GB

**HDD Space used:**

- Cinnamon: 7.3GB
- MATE: 7.5GB
- Xfce: 7.6GB

**Comment by clefebvre** [comment]
I agree with the recommended specs though, I'll rephrase the way it's written and put more emphasis on them. It doesn't really matter how low the system can run in since the experience won't be comfortable. It will be mentioned but made less prominent.

**Comment by clefebvre** [comment]
That said it's not that relevant how little you need to just install and start the OS if you can't use it comfortably. I'll update the specs.

Also, we recommend making timeshift snapshots so we need to account for that. 1 snapshot brings the 7.3GB used by Cinnamon to a 14GB footprint. It basically doubles it for the first snapshot, and after that it's incremental since it only preserves the differences. Mozilla can take a few GB in cache, Flatpak can add a few GB in runtimes... it's reasonable to think normal usage would require up to 10GB space, doubled to 20GB.

Adding Steam, extra apps, documents, downloads we can push this easily to 100GB.

**System Requirements**

- 2GB RAM (4GB recommended for a comfortable usage).
- 20GB of disk space (100GB recommended).
- 1024×768 resolution (on lower resolutions, press ALT to drag windows with the mouse if they don’t fit in the screen).

**Comment by clefebvre** [comment]
Updated.
